version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: elasticsearch-container
    environment:
      - discovery.type=single-node
    ports:
      # http://localhost:9200
      - "9200:9200"